version: '3.5'

networks:
  malcolm_network:
    external: true

services:
  movies_web:
    container_name: movies_web
    env_file: .env
    build: .
    restart: always
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
    ports:
      - 3006:3000
    depends_on:
      - movies_db
    networks:
      - malcolm_network
  movies_db:
    container_name: movies_db
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - malcolm_network

volumes:
  db-data: